
package com.example.demo.wbservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WorkOrderServiceItfPortType", targetNamespace = "http://itf.workorder.bs.nc/WorkOrderServiceItf")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WorkOrderServiceItfPortType {


    /**
     * 
     * @param string
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:repairInsert")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "repairInsert", targetNamespace = "http://itf.workorder.bs.nc/WorkOrderServiceItf", className = "nc.bs.workorder.itf.RepairInsert")
    @ResponseWrapper(localName = "repairInsertResponse", targetNamespace = "http://itf.workorder.bs.nc/WorkOrderServiceItf", className = "nc.bs.workorder.itf.RepairInsertResponse")
    public String repairInsert(
            @WebParam(name = "string", targetNamespace = "")
                    String string);

    /**
     * 
     * @param string
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:repairDelete")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "repairDelete", targetNamespace = "http://itf.workorder.bs.nc/WorkOrderServiceItf", className = "nc.bs.workorder.itf.RepairDelete")
    @ResponseWrapper(localName = "repairDeleteResponse", targetNamespace = "http://itf.workorder.bs.nc/WorkOrderServiceItf", className = "nc.bs.workorder.itf.RepairDeleteResponse")
    public String repairDelete(
            @WebParam(name = "string", targetNamespace = "")
                    String string);

    /**
     * 
     * @param string
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:repairUpdate")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "repairUpdate", targetNamespace = "http://itf.workorder.bs.nc/WorkOrderServiceItf", className = "nc.bs.workorder.itf.RepairUpdate")
    @ResponseWrapper(localName = "repairUpdateResponse", targetNamespace = "http://itf.workorder.bs.nc/WorkOrderServiceItf", className = "nc.bs.workorder.itf.RepairUpdateResponse")
    public String repairUpdate(
            @WebParam(name = "string", targetNamespace = "")
                    String string);

}
