
package com.example.demo.wbservice;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WorkOrderServiceItf", targetNamespace = "http://itf.workorder.bs.nc/WorkOrderServiceItf", wsdlLocation = "file:/E:/nc.bs.workorder.itf.wsdl")
public class WorkOrderServiceItf
    extends Service
{

    private final static URL WORKORDERSERVICEITF_WSDL_LOCATION;
    private final static WebServiceException WORKORDERSERVICEITF_EXCEPTION;
    private final static QName WORKORDERSERVICEITF_QNAME = new QName("http://itf.workorder.bs.nc/WorkOrderServiceItf", "WorkOrderServiceItf");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.43.63/uapws/service/nc.bs.workorder.itf.WorkOrderServiceItf?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WORKORDERSERVICEITF_WSDL_LOCATION = url;
        WORKORDERSERVICEITF_EXCEPTION = e;
    }

    public WorkOrderServiceItf() {
        super(__getWsdlLocation(), WORKORDERSERVICEITF_QNAME);
    }

    public WorkOrderServiceItf(WebServiceFeature... features) {
        super(__getWsdlLocation(), WORKORDERSERVICEITF_QNAME, features);
    }

    public WorkOrderServiceItf(URL wsdlLocation) {
        super(wsdlLocation, WORKORDERSERVICEITF_QNAME);
    }

    public WorkOrderServiceItf(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WORKORDERSERVICEITF_QNAME, features);
    }

    public WorkOrderServiceItf(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WorkOrderServiceItf(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WorkOrderServiceItfPortType
     */
    @WebEndpoint(name = "WorkOrderServiceItfSOAP11port_http")
    public WorkOrderServiceItfPortType getWorkOrderServiceItfSOAP11PortHttp() {
        return super.getPort(new QName("http://itf.workorder.bs.nc/WorkOrderServiceItf", "WorkOrderServiceItfSOAP11port_http"), WorkOrderServiceItfPortType.class);
    }

    private static URL __getWsdlLocation() {
        if (WORKORDERSERVICEITF_EXCEPTION!= null) {
            throw WORKORDERSERVICEITF_EXCEPTION;
        }
        return WORKORDERSERVICEITF_WSDL_LOCATION;
    }

}
